[features]
seeds = true
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
update_root = "ts-node ../../clients/ts/compute_and_update_roots.ts"
