[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
incognito = "4N49EyRoX9p9zoiv1weeeqpaJTGbEHizbzZVgrsrVQeC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "5QvQbnrL7fKpM5pCMS3zNqgTK8ALNkgHgRvgd49YF7v4"
program = "../escrow/target/deploy/escrow.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/alex/Desktop/incognito-protocol-1/contracts/incognito/artifacts/arcium_program_0.3.0.so"






# [[test.validator.account]]
# address = "CXTkGkpEXK3GsDGuHL8dhEXShYAnY6z6aLAA7z6HxVz7"
# filename = "artifacts/wallet_acc_CXTk_xVz7.json"
# 
# [[test.validator.account]]
# address = "7RjHsZ1WAYWJc5ge1dh3rR3ZndwqrRrGRzL117sQhH7S"
# filename = "artifacts/wallet_acc_callback_7RjH_hH7S.json"
# 
# [[test.validator.account]]
# address = "4tpLE1z2925WKPQ6nwjRARRmgJyLfy8NaegkBogEPaEH"
# filename = "artifacts/arx_ata_CXTk_xVz7.json"
# 
# [[test.validator.account]]
# address = "FJY4VtVChyTFg51Gsx1YPiJjAfyJFL2tF8t1rhqcACqX"
# filename = "artifacts/operator_acc_CXTk_xVz7.json"
# 
# [[test.validator.account]]
# address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
# filename = "artifacts/arx_node_CXTk_xVz7.json"
# 
# [[test.validator.account]]
# address = "7FeAQrcYZednD7zev5tioFvJ1sxsiLYpXCJms1cJGXEC"
# filename = "artifacts/wallet_acc_7FeA_GXEC.json"
# 
# [[test.validator.account]]
# address = "CSQsNoDccR1PTt8AeurTQWLHBvbHeEEzNpAtXYckqDxJ"
# filename = "artifacts/wallet_acc_callback_CSQs_qDxJ.json"
# 
# [[test.validator.account]]
# address = "2RUqfQbWbgtSY8TSwGCCJhFdT2z3iuKZjtxagSvYjxaR"
# filename = "artifacts/arx_ata_7FeA_GXEC.json"
# 
# [[test.validator.account]]
# address = "DM6gGpfnaPAZanY34gVANARzrx85nhHewJV8wBmiVL6F"
# filename = "artifacts/operator_acc_7FeA_GXEC.json"
# 
# [[test.validator.account]]
# address = "XdfSwb8ZajhN7CerfBSJVhyfx5fyLtv34QVKSRgMFA9"
# filename = "artifacts/arx_node_7FeA_GXEC.json"
